#!/bin/sh

# Define color variables for printing messages with color
RED='\033[0;31m'
GREEN='\033[0;32m'
RESET='\033[0m'

# auto format the code
echo "Running black to format code..."
black src

# auto sort the import order
echo "Running isort to sort imports..."
isort src

# detect secrets
echo "Running Yelp/detect-secrets..."
git diff --staged --name-only -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline
detect_secret_code=$?
if [ $detect_secret_code -ne 0 ]; then
  echo "${RED}detect-secrets failed. Please check secrets or upgrade baseline before committing.${RESET}"
  exit 1
fi

# Run lint check
echo "Running flake8 lint checks..."
lint_output=$(flake8 src)
lint_exit_code=$?

echo "$lint_output"

if [ $lint_exit_code -ne 0 ]; then
  echo "${RED}flake8 lint failed. Please fix the lint issues before committing.${RESET}"
  exit 1
fi

echo "${GREEN}flake8 lint check passed.${RESET}"
