#!/usr/bin/env bash

# auto format the code
black src
# auto sort the import order
isort src
# Run lint check
lint_output=$(flake8 src)
lint_exit_code=$?

echo "$lint_output"

# Check the pylint exit code
if [ $lint_exit_code -ne 0 ]; then
  echo "flake8 lint failed. Please fix the lint issues before committing."
  exit 1
fi

echo "flake8 lint check passed."
