"""Create user table

Revision ID: 08daa06c01b0
Revises: 
Create Date: 2024-03-03 21:09:00.546779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08daa06c01b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=192), nullable=False),
    sa.Column('salt', sa.String(length=192), nullable=False),
    sa.Column('admin_flag', sa.Boolean(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
