"""set nullable

Revision ID: 1b85be239d9e
Revises: dbe74df1b446
Create Date: 2024-03-13 15:13:21.812221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b85be239d9e'
down_revision = 'dbe74df1b446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=192),
               nullable=True)
        batch_op.alter_column('salt',
               existing_type=sa.VARCHAR(length=192),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('salt',
               existing_type=sa.VARCHAR(length=192),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=192),
               nullable=False)

    # ### end Alembic commands ###
