"""delete foreign key constraints in configuration table

Revision ID: 33e88747295b
Revises: 5b4ebbe7c21c
Create Date: 2024-04-18 13:47:04.285656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e88747295b'
down_revision = '5b4ebbe7c21c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.drop_constraint('configurations_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('configurations_case_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.create_foreign_key('configurations_case_id_fkey', 'visit_occurrence', ['case_id'], ['visit_occurrence_id'])
        batch_op.create_foreign_key('configurations_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
