"""update diagnose table

Revision ID: 5e61a2323099
Revises: aeaace325f6d
Create Date: 2024-05-11 15:55:40.366577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e61a2323099'
down_revision = 'aeaace325f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnose', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('diagnosis', sa.JSON(), nullable=False))
        batch_op.drop_column('diagosis')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnose', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagosis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.drop_column('diagnosis')
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
