"""Update diagnose table add answer_config_id and answer fields

Revision ID: 65d25ff61bc8
Revises: 4ec8cd100e21
Create Date: 2024-06-26 15:16:49.654496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65d25ff61bc8'
down_revision = '4ec8cd100e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnose', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_config_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('answer', sa.JSON(), nullable=True))
        batch_op.alter_column('diagnosis',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               comment='deprecated')
        batch_op.alter_column('other',
               existing_type=sa.VARCHAR(length=1024),
               comment='deprecated',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnose', schema=None) as batch_op:
        batch_op.alter_column('other',
               existing_type=sa.VARCHAR(length=1024),
               comment=None,
               existing_comment='deprecated',
               existing_nullable=True)
        batch_op.alter_column('diagnosis',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               comment=None,
               existing_comment='deprecated')
        batch_op.drop_column('answer')
        batch_op.drop_column('answer_config_id')

    # ### end Alembic commands ###
