"""remove foreign key relationship in diagnose and config

Revision ID: 6999a74674f3
Revises: daa3761eec6d
Create Date: 2024-05-16 15:03:00.735645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6999a74674f3'
down_revision = 'daa3761eec6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnose', schema=None) as batch_op:
        batch_op.drop_constraint('diagnose_task_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnose', schema=None) as batch_op:
        batch_op.create_foreign_key('diagnose_task_id_fkey', 'configuration', ['task_id'], ['id'])

    # ### end Alembic commands ###
