"""Create config table

Revision ID: 734fdb757341
Revises: ef7467079fda
Create Date: 2024-04-16 15:05:16.978444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734fdb757341'
down_revision = 'ef7467079fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('path_config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['visit_occurrence.visit_occurrence_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configurations')
    # ### end Alembic commands ###
