"""Create system config table

Revision ID: 887a81dd7200
Revises: 8f59b99351a3
Create Date: 2024-04-29 16:21:15.514282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887a81dd7200'
down_revision = '8f59b99351a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('id', sa.String(length=15), nullable=False),
    sa.Column('json_config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_config')
    # ### end Alembic commands ###
