"""add modified_timestamp to user table 

Revision ID: 954263ab2168
Revises: 08daa06c01b0
Create Date: 2024-03-03 21:26:53.824325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954263ab2168'
down_revision = '08daa06c01b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modified_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('modified_timestamp')

    # ### end Alembic commands ###
