"""Create diagonose table

Revision ID: aeaace325f6d
Revises: 887a81dd7200
Create Date: 2024-05-10 15:00:18.621278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeaace325f6d'
down_revision = '887a81dd7200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnose',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('display_configuration', sa.JSON(), nullable=True),
    sa.Column('diagosis', sa.JSON(), nullable=False),
    sa.Column('other', sa.String(length=1024), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('modified_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnose')
    # ### end Alembic commands ###
