"""rename configuration table to display_config table

Revision ID: b146ce97647e
Revises: d141f5050bd6
Create Date: 2024-07-05 15:50:29.722398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b146ce97647e'
down_revision = 'd141f5050bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('configuration', 'display_config')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('display_config', 'configuration')
    # ### end Alembic commands ###
