"""rename diagnose table to answer table

Revision ID: c24303936875
Revises: b146ce97647e
Create Date: 2024-07-05 15:53:52.671588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c24303936875'
down_revision = 'b146ce97647e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('diagnose', 'answer')

# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('answer', 'diagnose')
    # ### end Alembic commands ###
