"""fix concept_synonym ddl v2

Revision ID: d0c7c26f5c10
Revises: ef7467079fda
Create Date: 2024-04-15 17:01:00.316218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c7c26f5c10'
down_revision = 'ef7467079fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concept_synonym', schema=None) as batch_op:
        batch_op.drop_constraint('concept_synonym_pkey', type_='primary')
        batch_op.create_primary_key('concept_synonym_pkey', ['concept_id', 'concept_synonym_name', 'language_concept_id'])
        batch_op.create_unique_constraint(None, ['concept_id', 'concept_synonym_name', 'language_concept_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concept_synonym', schema=None) as batch_op:
        batch_op.drop_constraint('concept_synonym_pkey', type_='primary')
        batch_op.create_primary_key('concept_synonym_pkey', ['concept_id', 'concept_synonym_name'])
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
