"""change path config into nullable

Revision ID: d126cdd7b0f1
Revises: f1dcd3927546
Create Date: 2024-04-19 11:28:26.765792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd126cdd7b0f1'
down_revision = 'f1dcd3927546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concept_synonym', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['concept_id', 'concept_synonym_name', 'language_concept_id'])

    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.alter_column('path_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.alter_column('path_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)

    with op.batch_alter_table('concept_synonym', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
