"""remove diagnose and others columns

Revision ID: d141f5050bd6
Revises: 65d25ff61bc8
Create Date: 2024-07-02 16:16:55.095767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd141f5050bd6'
down_revision = '65d25ff61bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnose', schema=None) as batch_op:
        batch_op.drop_column('diagnosis')
        batch_op.drop_column('other')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnose', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other', sa.VARCHAR(length=1024), autoincrement=False, nullable=True, comment='deprecated'))
        batch_op.add_column(sa.Column('diagnosis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='deprecated'))

    # ### end Alembic commands ###
