"""add user fields

Revision ID: dbe74df1b446
Revises: 954263ab2168
Create Date: 2024-03-13 14:48:23.246681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe74df1b446'
down_revision = '954263ab2168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('employer', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('area_of_clinical_ex', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_column('active')
        batch_op.drop_column('area_of_clinical_ex')
        batch_op.drop_column('employer')
        batch_op.drop_column('position')

    # ### end Alembic commands ###
