"""fix concept_synonym ddl

Revision ID: ef7467079fda
Revises: 126b72179cc0
Create Date: 2024-04-15 15:58:56.433331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7467079fda'
down_revision = '126b72179cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
